title: "Murderhungry"
email: info@eppleton.de
timezone: Europe/Berlin
baseurl: "/"
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: toni
paginate: 30
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
# google_analytics: UA-211898691-1
# Authors
authors:
  toni:
    name: toni
    display_name: toni
    avatar: 'assets/images/toni.png'
    email: toni.epple@eppleton.de
    web: https://www.eppleton.de
    twitter: https://twitter.com/monacotoni
    description: "I'm Toni Epple, a software developer who loves hosting murder mystery parties based in Munich, Germany. I'm the creator of the Murderhungry Blog and hopefully the App."

# Social
social:
  instagram: https://www.instagram.com/murderhungry/
  facebook: https://www.facebook.com/mysterydinnerapp
  twitter: https://twitter.com/murderhungryapp

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives

include:
  .well-known
